### ISSUE TITLE
Compiled Version

### ISSUE THREAD

**Issue by p0wer0n** [fewizz/Svarka#1]
Could you please provide links to pre-built versions of this project for 1.9.4 and/or 1.10.2?
Thanks

**Comment by fewizz** [comment]
Atm works only 1.9.4(atm!), and most CB patches not imported... WIP.

**Comment by p0wer0n** [comment]
Have you gotten some the CB patches to work?

**Comment by fewizz** [comment]
OC. Most WE commands already work on Svarka 1.9.4.

**Comment by p0wer0n** [comment]
Do you have a test .jar that I can use? I can't get the project to compile.

**Comment by fewizz** [comment]
No. Not now. :disappointed: .

**Comment by WinggedPhantom** [comment]
When will this be available for 1.10.2 and I can't compile it as well

**Comment by fewizz** [comment]
Did you init submodules?

**Comment by WinggedPhantom** [comment]
I'm not sure how to, is there any way I could get into contact with you? Thanks.

**Comment by fewizz** [comment]
Anyway, Svarka is unplayable atm..
